from pyspark.sql.types import *

bq_table_name = "endereco"
columns_type = {
    "hash_key": StringType,
    "source": StringType,
    "e_id_endereco": IntegerType,
    "e_id_pessoafisica": IntegerType,
    "e_id_estabelecimento": IntegerType,
    "e_tipoconta": IntegerType,
    "e_id_tipoendereco": IntegerType,
    "e_tipologradouro": StringType,
    "e_nomelogradouro": StringType,
    "e_numeroendereco": IntegerType,
    "e_complementoendereco": StringType,
    "e_bairro": StringType,
    "e_cidade": StringType,
    "e_cep": StringType,
    "e_uf": StringType,
    "e_pais": StringType,
    "e_referencialocalizacao": StringType,
    "e_residencia": IntegerType,
    "e_temporesidenciaanos": IntegerType,
    "e_temporesidenciameses": IntegerType,
    "e_enderecoanterior": StringType,
    "e_temporesidencia": StringType,
    "e_datainclusao": TimestampType,
    "e_flagbloqueado": BooleanType,
    "e_dataultimaatualizacao": TimestampType,
    "te_id_tipoendereco": IntegerType,
    "te_nome": StringType,
    "te_descricao": StringType,
    "dh_relatorio": TimestampType,
    "operation": StringType,
    "operation_sequence": IntegerType,
    "production_date": DateType,
}
