from pyspark.sql.types import *

bq_table_name = "integracao_grade"
columns_type = {
	"hash_key": StringType,
	"source": StringType,
	"ig_id_grade": IntegerType,
	"ig_id_conta": IntegerType,
	"ig_idstatusintegracao": IntegerType,
	"ig_statusintegracao": StringType,
	"ig_datacadastramento": TimestampType,
	"ig_estabelecimento": StringType,
	"ig_email": StringType,
	"ig_tipodocumento": IntegerType,
	"ig_cpf": StringType,
	"ig_idproduto": IntegerType,
	"ig_motivoemissaocartao": StringType,
	"ig_motivoreemissaocartao": StringType,
	"ig_statuscartaoantigo": IntegerType,
	"ig_statuscartaonovo": IntegerType,
	"ig_limiteinterno": DoubleType,
	"ig_limite": DoubleType,
	"ig_datafimvalidade": TimestampType,
	"ig_portador": IntegerType,
	"ig_cartaonovo": StringType,
	"ig_cartaoantigo": StringType,
	"ig_bloqueiocartaoantigo": StringType,
	"ig_chapa": StringType,
	"ig_chapapromotor": StringType,
	"ig_conta": StringType,
	"ig_datacriacaoconta": TimestampType,
	"ig_tipocobranca": StringType,
	"ig_codanuidade": StringType,
	"ig_coddesconto": StringType,
	"ig_codaceite": StringType,
	"ig_codlogonovo": StringType,
	"ig_dataenvio": TimestampType,
	"ig_serial_tablet": StringType,
	"ig_observacao": StringType,
	"ig_id_cartao": IntegerType,
	"dh_relatorio": TimestampType,
	"operation": StringType,
	"operation_sequence": IntegerType,
	"production_date": DateType,
}
