from pyspark.sql.types import *

bq_table_name = "transacao_corrente"
columns_type = {
	"hash_key": StringType,
	"source": StringType,
	"tc_id_transacao": LongType,
	"tc_id_tipotransacao": IntegerType,
	"tc_id_emissor": IntegerType,
	"tc_id_produto": IntegerType,
	"tc_id_conta": IntegerType,
	"tc_portador": IntegerType,
	"tc_sequencialcartao": IntegerType,
	"tc_datavencimentoreal": TimestampType,
	"tc_datavencimentopadrao": StringType,
	"tc_datageracao": TimestampType,
	"tc_valor": DoubleType,
	"tc_historico": StringType,
	"tc_statuscontabil": IntegerType,
	"tc_statusgerencial": IntegerType,
	"tc_id_eventoexterno": IntegerType,
	"tc_dataorigem": TimestampType,
	"tc_statusconta": IntegerType,
	"tc_faturado": IntegerType,
	"tc_id_estabelecimento": IntegerType,
	"tc_datafaturamento": TimestampType,
	"tc_complemento": StringType,
	"tc_id_transacaoestorno": LongType,
	"tc_flagestornado": IntegerType,
	"tc_parcela": IntegerType,
	"tc_plano": IntegerType,
	"tc_id_estabelecimento_visa": IntegerType,
	"tc_id_planocredito": IntegerType,
	"tc_id_processoprocedure": IntegerType,
	"tc_datavencpadrao": TimestampType,
	"tc_id_taxajurosapropriacao": IntegerType,
	"dh_relatorio": TimestampType,
	"operation": StringType,
	"operation_sequence": IntegerType,
	"production_date": DateType,
}
