from pyspark.sql.types import *

bq_table_name = "embossing_inconsistente"
columns_type = {
	"hash_key": StringType,
	"source": StringType,
	"id_embossinginconsistente": IntegerType,
	"id_embossinggrupo": IntegerType,
	"id_cartao": IntegerType,
	"id_produto": IntegerType,
	"id_conta": IntegerType,
	"sequencialcartao": StringType,
	"datageracao": StringType,
	"dataliberacao": StringType,
	"id_embossingmensagens": IntegerType,
	"id_area": IntegerType,
	"flaginconsistenciaresolvida": BooleanType,
	"datavalidade": StringType,
	"portador": IntegerType,
	"estagio": StringType,
	"arquivolote": StringType,
	"conta": IntegerType,
	"codigodesbloqueio": StringType,
	"datanascimento": StringType,
	"vencimento1": StringType,
	"numeroacc": DoubleType,
	"datacadastramento": StringType,
	"nomeplastico": StringType,
	"nomelogradouro": StringType,
	"numeroendereco": StringType,
	"complementoendereco": StringType,
	"bairro": StringType,
	"cidade": StringType,
	"cep": StringType,
	"uf": StringType,
	"limiteglobalcredito": DoubleType,
	"limitesaquenacglobal": DoubleType,
	"arquivoembossingproduto": StringType,
	"arquivoembossingplastico": StringType,
	"arquivoembossing": StringType,
	"nometitular": StringType,
	"berco": StringType,
	"nomereferencia1": StringType,
	"nomereferencia2": StringType,
	"cpf": StringType,
	"nomeproduto": StringType,
	"flagcpfembossing": BooleanType,
	"cpfembossing": StringType,
	"flagdeficientevisual": BooleanType,
	"dh_relatorio": StringType,
	"operation": StringType,
	"operation_sequence": IntegerType,
	"production_date": DateType,
}
