from pyspark.sql.types import *

bq_table_name = "evento_externo_pagamento"
columns_type = {
	"hash_key": StringType,
	"source": StringType,
	"ep_id_eventopagamento": IntegerType,
	"ep_banco": IntegerType,
	"ep_datamovimento": TimestampType,
	"ep_datapagamento": TimestampType,
	"ep_nossonumero": DoubleType,
	"ep_arquivocobrancabancaria": StringType,
	"ep_datavencimento": TimestampType,
	"ep_valorpago": DoubleType,
	"ep_numerodocumento": DoubleType,
	"ep_cartao": StringType,
	"ep_id_movimentopagamentopendente": IntegerType,
	"ep_lote": IntegerType,
	"ep_defasagemcobranca": IntegerType,
	"ep_meioliquidacao": StringType,
	"ep_id_estabelecimento": IntegerType,
	"ep_id_autorizacao": IntegerType,
	"ep_id_conta": IntegerType,
	"ep_id_operacao": IntegerType,
	"ep_codigoautenticacao": StringType,
	"ep_dataentradapagamento": TimestampType,
	"ep_datavencimentopadrao": StringType,
	"ep_datavencimentoreal": TimestampType,
	"ep_origem": StringType,
	"ep_origemresolucao": StringType,
	"ep_restituicaosaque": DoubleType,
	"ep_status": IntegerType,
	"ep_dataprocessamentolojista": TimestampType,
	"ep_id_borderaux": IntegerType,
	"ep_dataprocessamentolojista2": TimestampType,
	"ep_codigoautorizacao": StringType,
	"ep_statuslojista": IntegerType,
	"ep_mcc": IntegerType,
	"ep_codigomoeda": IntegerType,
	"ep_nome_estabelecimento_visa": StringType,
	"ep_id_estabelecimento_visa": IntegerType,
	"ep_id_incoming": IntegerType,
	"ep_valordolar": DoubleType,
	"ep_id_cartao": IntegerType,
	"ep_id_eventoexternoredecompartilhada": IntegerType,
	"ep_id_emissorredecompartilhada": IntegerType,
	"ep_id_estabelecimento_externo": IntegerType,
	"ep_codautredecompartilhada": StringType,
	"ep_databaixa": TimestampType,
	"ep_datavencpadrao": TimestampType,
	"ep_flagusoudiasperdao": BooleanType,
	"ep_datapagamentoreal": TimestampType,
	"dh_relatorio": TimestampType,
	"operation": StringType,
	"operation_sequence": IntegerType,
	"production_date": DateType
}
