from pyspark.sql.types import *

bq_table_name = "limite_disponibilidade"
columns_type = {
    "hash_key": StringType,
    "source": StringType,
    "ld_id_conta": IntegerType,
    "ld_id_emissor": IntegerType,
    "ld_limitesaquenacperiodo": DoubleType,
    "ld_limitesaquenacglobal": DoubleType,
    "ld_limitecompranac": DoubleType,
    "ld_limiteparceladonac": DoubleType,
    "ld_limitesaqueintperiodo": DoubleType,
    "ld_limitesaqueintglobal": DoubleType,
    "ld_limitecompraint": DoubleType,
    "ld_limiteparceladoint": DoubleType,
    "ld_limiteglobalcredito": DoubleType,
    "ld_disponibsaquenacglobal": DoubleType,
    "ld_disponibcompranac": DoubleType,
    "ld_disponibparceladonac": DoubleType,
    "ld_disponibsaqueintglobal": DoubleType,
    "ld_disponibcompraint": DoubleType,
    "ld_disponibparcelasnac": DoubleType,
    "ld_disponibglobalcredito": DoubleType,
    "ld_limiteparcelasnac": DoubleType,
    "ld_limiteparcelasint": DoubleType,
    "ld_limitepontuacao": DoubleType,
    "ld_margemconsignada": DoubleType,
    "ld_tipotarifa": StringType,
    "ld_percdescontotarifa": IntegerType,
    "ld_limitemaximo": DoubleType,
    "dh_relatorio": TimestampType,
    "operation": StringType,
    "operation_sequence": IntegerType,
    "production_date": DateType,
}