from pyspark.sql.types import *

bq_table_name = "log_atendimento"
columns_type = {
    "hash_key": StringType,
    "source": StringType,
    "la_id_logatendimento": IntegerType,
    "la_id_tipoligacao": IntegerType,
    "la_arquivowav": StringType,
    "la_id_conta": IntegerType,
    "la_id_estabelecimento": IntegerType,
    "la_id_produto": IntegerType,
    "la_datahorainicio": TimestampType,
    "la_datahorafim": TimestampType,
    "la_nomeatendente": StringType,
    "la_nomemaquina": StringType,
    "la_id_proposta": IntegerType,
    "la_id_gerenciamentocobranca": IntegerType,
    "la_flagatendetelefoneinativo": IntegerType,
    "la_id_acionamento": IntegerType,
    "la_id_acao": IntegerType,
    "la_datavencimentocobranca": StringType,
    "la_datavencimentopadrao": StringType,
    "la_id_motivo": IntegerType,
    "la_cpf": StringType,
    "la_telefone": StringType,
    "la_flagexistetelefone": BooleanType,
    "la_ddd": StringType,
    "mfl_motivo_ligacao": StringType,
    "dh_relatorio": TimestampType,
    "operation": StringType,
    "operation_sequence": IntegerType,
    "production_date": DateType,
}
