from pyspark.sql.types import *

bq_table_name = "operacoes_bancarias"
columns_type = {
	"hash_key": StringType,
	"source": StringType,
	"ob_id_operacao_bancaria": IntegerType,
	"ob_id_tipo_operacao_bancaria": IntegerType,
	"tob_tipo_operacao_bancaria": StringType,
	"ob_id_conta_origem": IntegerType,
	"ob_id_dados_bancarios_conta": IntegerType,
	"ob_id_documento": LongType,
	"ob_id_conta_destino": IntegerType,
	"ob_id_cartao_origem": IntegerType,
	"ob_id_cartao_destino": IntegerType,
	"ob_id_celular_recarga": LongType,
	"ob_id_operacao_bancaria_original": IntegerType,
	"ob_nome_pagador": StringType,
	"ob_banco_pagador": StringType,
	"ob_agencia_pagador": StringType,
	"ob_conta_pagador": StringType,
	"ob_dv_conta_pagador": StringType,
	"ob_nome_beneficiario": StringType,
	"ob_banco_beneficiario": StringType,
	"ob_agencia_beneficiario": StringType,
	"ob_conta_beneficiario": StringType,
	"ob_dv_conta_beneficiario": StringType,
	"ob_cpf_cnpj_beneficiario": StringType,
	"ob_id_evento_ajuste_origem": LongType,
	"ob_id_evento_ajuste_destino": LongType,
	"ob_id_externo": StringType,
	"ob_cod_ispb": StringType,
	"ob_valor_operacao": DoubleType,
	"ob_valor_tarifa": DoubleType,
	"ob_data_hora_operacao": TimestampType,
	"ob_data_agendamento": TimestampType,
	"ob_data_realizacao": TimestampType,
	"ob_status_operacao": IntegerType,
	"ob_numero_bilhete_unico": LongType,
	"ob_observacao": StringType,
	"ob_operadora": StringType,
	"ob_celular": StringType,
	"ob_ddd": StringType,
	"ob_chave_pix_beneficiario": StringType,
	"ob_id_ajuste_conta_debito": StringType,
	"dh_relatorio": TimestampType,
	"operation": StringType,
	"operation_sequence": IntegerType,
	"production_date": DateType,
}
