from pyspark.sql.types import *

bq_table_name = "origem_comercial"
columns_type = {
	"hash_key": StringType,
	"source": StringType,
	"oc_id_origemcomercial": IntegerType,
	"oc_id_emissor": IntegerType,
	"oc_nome": StringType,
	"oc_descricao": StringType,
	"oc_id_promotorvenda": IntegerType,
	"oc_flagpreaprovado": BooleanType,
	"oc_flagaprovacaoimediata": BooleanType,
	"oc_nomefantasiaplastico": StringType,
	"oc_id_estabelecimento": IntegerType,
	"oc_flagsituacaoorigem": BooleanType,
	"oc_flagcartaoprovisorio": BooleanType,
	"oc_flagcartaodefinitivo": BooleanType,
	"oc_usuario": StringType,
	"oc_senha": StringType,
	"oc_origemexterna": BooleanType,
	"oc_flagmodificado": BooleanType,
	"oc_id_tipoorigem": IntegerType,
	"oc_tipopessoa": IntegerType,
	"oc_responsavel": StringType,
	"oc_flagenviafaturausuario": IntegerType,
	"oc_flagcreditofaturamento": IntegerType,
	"oc_flagconcedelimiteprovisorio": BooleanType,
	"oc_id_grupoorigemcomercial": IntegerType,
	"oc_flagdigitalizardoc": BooleanType,
	"oc_flagembossingloja": BooleanType,
	"oc_flagconsultaprevia": BooleanType,
	"oc_flagembossacartaodefinitivo": BooleanType,
	"oc_flagenviasms": BooleanType,
	"gc_id_grupoorigemcomercial": IntegerType,
	"gc_descricao": StringType,
	"tg_id_tipoorigem": IntegerType,
	"tg_descricao": StringType,
	"tg_flagrelatoriotad": BooleanType,
	"dh_relatorio": TimestampType,
	"operation": StringType,
	"operation_sequence": IntegerType,
	"production_date": DateType,
}
