from pyspark.sql.types import *

bq_table_name = "parcelamento_fatura"
columns_type = {
	"hash_key": StringType,
	"source": StringType,
	"pf_id_parcelamento": IntegerType,
	"pf_id_conta": IntegerType,
	"pf_id_eventocompra": IntegerType,
	"pf_datavencimentopadrao": TimestampType,
	"pf_datamovimento": TimestampType,
	"pf_id_regracampanha": IntegerType,
	"pf_regra": StringType,
	"pf_statusadesao": IntegerType,
	"pf_descricaostatusadesao": StringType,
	"pf_id_servicotipo": IntegerType,
	"pf_tiposervico": StringType,
	"pf_totalparcelamento": DoubleType,
	"pf_saldoatualfatura": DoubleType,
	"pf_valorentrada": DoubleType,
	"pf_flagcomentrada": BooleanType,
	"pf_dataprocessamentoadesao": TimestampType,
	"pf_quantidadeparcelas": IntegerType,
	"pf_valorparcela": DoubleType,
	"pf_taxarefinanciamento": DoubleType,
	"pf_custoefetivototal": DoubleType,
	"pf_valoriof": DoubleType,
	"pf_valortac": DoubleType,
	"pf_valortotalrefinanciamento": DoubleType,
	"dh_relatorio": TimestampType,
	"operation": StringType,
	"operation_sequence": IntegerType,
	"production_date": DateType,
}
