from pyspark.sql.types import *

bq_table_name = "seguro_estabelecimento"
columns_type = {
	"hash_key": StringType,
	"source": StringType,
	"es_id_estabelecimento": IntegerType,
	"es_id_emissor": IntegerType,
	"es_no_cnpj": StringType,
	"es_cd_estabelecimento": StringType,
	"es_nm_estabelecimento": StringType,
	"es_id_endereco": IntegerType,
	"es_id_contato": IntegerType,
	"es_fl_ativo": BooleanType,
	"es_no_serienfe": StringType,
	"es_cd_servico": StringType,
	"edr_id_endereco": IntegerType,
	"edr_nm_logradouro": StringType,
	"edr_no_logradouro": StringType,
	"edr_dc_complemento": StringType,
	"edr_nm_bairro": StringType,
	"edr_nm_municipio": StringType,
	"edr_cd_uf": StringType,
	"edr_no_cep": StringType,
	"cnt_id_contato": IntegerType,
	"cnt_nm_contato": StringType,
	"cnt_no_ddd_telefone": IntegerType,
	"cnt_no_telefone": IntegerType,
	"cnt_no_ramal": StringType,
	"cnt_no_ddd_celular": IntegerType,
	"cnt_no_celular": IntegerType,
	"cnt_dc_email": StringType,
	"dh_relatorio": TimestampType,
	"operation": StringType,
	"operation_sequence": IntegerType,
	"production_date": DateType,
}
