from pyspark.sql.types import *

bq_table_name = "tipo_transacao"
columns_type = {
	"hash_key": StringType,
	"source": StringType,
	"tt_id_tipotransacao": IntegerType,
	"tt_tiporegistro": IntegerType,
	"tt_nome": StringType,
	"tt_flagcredito": BooleanType,
	"tt_flagextrato": BooleanType,
	"tt_operacao": BooleanType,
	"tt_tipoevento": StringType,
	"tt_descricao": StringType,
	"tt_descricaoabreviada": StringType,
	"tt_flagajuste": IntegerType,
	"tt_flagpagamento": BooleanType,
	"tt_flagcompra": BooleanType,
	"tt_flagcalculaencargos": IntegerType,
	"tt_flagiof": BooleanType,
	"tt_flagiss": BooleanType,
	"tt_d_c_co": StringType,
	"tt_dre": StringType,
	"tt_tipodre": StringType,
	"tt_tipotrans": StringType,
	"tt_flaginadimplencia": BooleanType,
	"tt_flagestornavelnaopagamento": BooleanType,
	"tt_flagacordo": BooleanType,
	"tt_classe": StringType,
	"tt_flagcomissaoacordo": BooleanType,
	"tt_flagextratodefault": BooleanType,
	"tt_id_componente": IntegerType,
	"dh_relatorio": TimestampType,
	"operation": StringType,
	"operation_sequence": IntegerType,
	"production_date": DateType,
}
